# Material ID : mp-961673

In [1]:
import json


# An optional utility to display a progress bar
# for long-running loops. `pip install tqdm`.
from tqdm import tqdm
#import atomate2.common.schemas.symmetry as acss
#!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester

api_key = "IDG8oerg7OP5AeRfbNjUZBb1Ad4Qke2l"
material_id = "mp-961673"

mpr = MPRester(api_key)

structure = mpr.get_structure_by_material_id(material_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Télécharger le fichier .cif

In [2]:
from pymatgen.io.cif import CifWriter
#from pymatgen.io.xyz import XYZ

CifWriter(structure).write_file(material_id+".cif")
#XYZ(structure).write_file(material_id+".xyz")

# Étude de la symmétrie

In [3]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

#Création d'un objet SpaceGroupAnalyzer
struct = SpacegroupAnalyzer(structure)
new_s  = SpacegroupAnalyzer(structure).get_primitive_standard_structure()
space_group = SpacegroupAnalyzer(new_s).get_space_group_symbol()
print("Molecule formula :",new_s.reduced_formula,"\t \t space group :", space_group)

Molecule formula : TiFeTe 	 	 space group : F-43m


In [4]:
from ipywidgets import Layout, widgets, interact
from IPython.display import display
from jupyter_jsmol.pymatgen import quick_view
from jupyter_jsmol import JsmolView

struct_conv = struct.get_conventional_standard_structure()
#récupération de la structure conventionnel qui correspond à la maille du fichier CIF symmetrized
struct_analyze = SpacegroupAnalyzer(struct_conv)

view = quick_view(structure, conventional=True, supercell=[2,2,2])
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [5]:
view.script("select all; label on; select tellurium; color lightgreen")

In [6]:
# récupération des opération de symmétrie
sym_op = struct_analyze.get_symmetry_operations()
for i in range(len(sym_op)):
    print("----", i, "----\n", sym_op[i])
"""
print(sym_op[24])#translation (tau [0.5 0.5 0])
print("__________")
print(sym_op[8]) #rot C3 [111]
print("__________")
print(sym_op[34]) #rot C3 [-11-1] + translation (tau [0.5 0.5 0])
"""
#récupération de tous les sites d'atome dans la maille cristalline
sites = struct_conv.sites 
print("\n",sites)

---- 0 ----
 Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]
---- 1 ----
 Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
---- 2 ----
 Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
---- 3 ----
 Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
---- 4 ----
 Rot:
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
---- 5 ----
 Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]
---- 6 ----
 Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
---- 7 ----
 Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
---- 8 ----
 Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]
---- 9 ----
 Rot:
[[ 0.  0. -1.]
 [ 0.  1.  0.]
 [-1.  0.  0.]]
tau
[0. 0. 0.]
---- 10 ----
 Rot:
[[ 0.  0.  1.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]
tau
[0. 0. 0.]
---- 11 ----
 Rot:
[[ 0.  0. -1.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]]
tau
[0. 0. 0.]
---- 12 ----
 Rot:
[[ 0.  0. -1.]
 [ 1.  0.  0.]
 [ 0. -1.  0.]]
tau
[0. 0. 0

# Premier élément de symétrie
Le premier élément de symétrie est une rotation d'ordre 3 dans la direction $<1 1 1>$.

La matrice qui représente cette opération de symétrie est la suivante : $$\left({\begin{array}{cc}
    0 & 0 & 1 \\
    1 & 0 & 0 \\
    0 & 1 & 0 \\
  \end{array} }\right)$$
  
C'est l'opération renseignée à la position 8 de la liste que l'on retrouve plus haut.
Cet élément de symétrie va être appliqué à l'atome $\textit{Ti}$ dont les coordonnées réduites sont : $(0 , 0 , 0.5)$

In [7]:
op1 = sym_op[8]
print(op1)
ti1 = sites[2]
atome = str(ti1.species)

print("\nCoordonnées réduites avant l'opération de symétrie sur l'atome de", atome[:2], " : ", ti1.frac_coords)
# application de l'opérateur de symétrie
ti1_afterop = op1.operate(ti1.frac_coords)
print("Coordonnées réduites après l'opération :", ti1_afterop)

Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0. 0. 0.]

Coordonnées réduites avant l'opération de symétrie sur l'atome de Ti  :  [0.  0.  0.5]
Coordonnées réduites après l'opération : [0.5 0.  0. ]


In [8]:
# représentation graphique
view = quick_view(struct_conv,supercell=[1,1,1])
display(view)
#view.script("select all; label on")
view.script('draw SYMOP 9 {atomno = 1}; select atomno=1; label on; select tellurium; color lightgreen')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Deuxième élément de symétrie
Le deuxième élément de symétrie est une translation dans la direction $<1 1 0>$. 

La matrice qui représente cette opération de symétrie est la matrice identité : $$\begin{pmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
  \end{pmatrix}$$ à laquelle on ajoute une translation $(0.5, 0.5, 0)$
  
L'équation est donc : $$\begin{pmatrix}  1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \end{pmatrix} 
\begin{pmatrix}  
x \\ 
y \\ 
z 
\end{pmatrix} + \begin{pmatrix}
    0.5 \\
    0.5 \\
    0 \\
  \end{pmatrix} = \begin{pmatrix}
   x+0.5 \\
   y+0.5 \\
   z \\
  \end{pmatrix}$$
  
C'est l'opération renseignée à la position 24 de la liste que l'on retrouve plus haut. Cet élément de symétrie va être appliqué à l'atome de $\textit{Fe}$ dont les coordonnées réduites sont : $(0.25 , 0.25, 0.25)$

In [9]:
op2 = sym_op[24] #rot C2 [011] * refl axe z
print(op2)
fe1 = sites[5]
atome = str(fe1.species)

print("\nCoordonnées réduites avant l'opération de symétrie sur l'atome de", atome[:2], " : ", fe1.frac_coords)
# application de l'opérateur de symétrie
fe1_afterop = op2.operate(fe1.frac_coords)
print("Coordonnées réduites après l'opération :", fe1_afterop)

Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ]

Coordonnées réduites avant l'opération de symétrie sur l'atome de Fe  :  [0.25 0.25 0.25]
Coordonnées réduites après l'opération : [0.75 0.75 0.25]


In [10]:
# représentation 3D graphique de l'opération
view = quick_view(struct_conv,supercell=[1,1,1])
display(view)
view.script('draw SYMOP 25 {atomno = 2}; select atomno=2; label on; select tellurium; color lightgreen')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

# Troisième élément de symétrie
Le troisième élément de symétrie est une rotation hélicoïdale $3_1$ dans la direction $<1 1 1>$. 

La matrice qui représente la rotation de cette opération de symétrie est la suivante : $$\begin{pmatrix}
    0 & 0 & 1 \\
    1 & 0 & 0 \\
    0 & 1 & 0
  \end{pmatrix}$$
Pour compléter l'opération de symmétrie, il faut appliquer une translation $(0, 0.5, 0.5)$.
  
L'équation est donc : $$\begin{pmatrix}  0 & 0 & 1 \\
    1 & 0 & 0 \\
    0 & 1 & 0 \end{pmatrix} 
\begin{pmatrix}  
x \\ 
y \\ 
z 
\end{pmatrix} + \begin{pmatrix}
    0 \\
    0.5 \\
    0.5 \\
  \end{pmatrix} = \begin{pmatrix}
   z \\
   x+0.5 \\
   y+0.5 \\
  \end{pmatrix}$$
  
C'est l'opération renseignée à la position 80 de la liste que l'on retrouve plus haut. Cet élément de symétrie va être appliqué à l'atome de $\textit{Te}$ dont les coordonnées réduites sont : $(0 , 0.5, 0.5)$

In [11]:
op3 = sym_op[80] 
print(op3)
te1 = sites[9]
atome = str(te1.species)

print("\nCoordonnées réduites avant l'opération de symétrie sur l'atome de", atome[:2], " : ", te1.frac_coords)
# application de l'opérateur de symétrie
te1_afterop = op3.operate(te1.frac_coords)
print("Coordonnées réduites après l'opération :", te1_afterop)

Rot:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
tau
[0.  0.5 0.5]

Coordonnées réduites avant l'opération de symétrie sur l'atome de Te  :  [0.  0.5 0.5]
Coordonnées réduites après l'opération : [0.5 0.5 1. ]


In [12]:
# représentation 3D graphique de l'opération
view = quick_view(struct_conv,supercell=[1,1,1])
display(view)
view.script('draw SYMOP 81 {atomno = 22}; select atomno=22; label on; select tellurium; color lightgreen')

JsmolView(layout=Layout(align_self='stretch', height='400px'))